# Generated by Django 4.2.6 on 2023-10-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_list", "0002_genres_movies_collections"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movies",
            name="uuid",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
